/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthNovaSenhaRouteImport } from './routes/auth_.nova-senha'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProcessamentoRouteImport } from './routes/_authenticated/processamento'
import { Route as AuthenticatedPlanosAcaoRouteImport } from './routes/_authenticated/planos-acao'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRhRouteImport } from './routes/_authenticated/painel-rh'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedOperacaoAssistidaRouteImport } from './routes/_authenticated/operacao-assistida'
import { Route as AuthenticatedOcorrenciasPontoRouteImport } from './routes/_authenticated/ocorrencias-ponto'
import { Route as AuthenticatedObservabilidadeRouteImport } from './routes/_authenticated/observabilidade'
import { Route as AuthenticatedNovaAusenciaRouteImport } from './routes/_authenticated/nova-ausencia'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedInteligenciaRouteImport } from './routes/_authenticated/inteligencia'
import { Route as AuthenticatedHomologacaoRouteImport } from './routes/_authenticated/homologacao'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDocumentacaoRouteImport } from './routes/_authenticated/documentacao'
import { Route as AuthenticatedDeployRouteImport } from './routes/_authenticated/deploy'
import { Route as AuthenticatedDashboardExecutivoRouteImport } from './routes/_authenticated/dashboard-executivo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComunicacoesRouteImport } from './routes/_authenticated/comunicacoes'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedBiExecutivoRouteImport } from './routes/_authenticated/bi-executivo'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedComunicacoesIndexRouteImport } from './routes/_authenticated/comunicacoes.index'
import { Route as AuthenticatedInteligenciaSupervisoresRouteImport } from './routes/_authenticated/inteligencia.supervisores'
import { Route as AuthenticatedInteligenciaQualidadeRouteImport } from './routes/_authenticated/inteligencia.qualidade'
import { Route as AuthenticatedInteligenciaGovernancaRouteImport } from './routes/_authenticated/inteligencia.governanca'
import { Route as AuthenticatedInteligenciaDashboardRouteImport } from './routes/_authenticated/inteligencia.dashboard'
import { Route as AuthenticatedInteligenciaConfiguracaoRouteImport } from './routes/_authenticated/inteligencia.configuracao'
import { Route as AuthenticatedInteligenciaAlertasRouteImport } from './routes/_authenticated/inteligencia.alertas'
import { Route as AuthenticatedCoordenacaoSupervisoresRouteImport } from './routes/_authenticated/coordenacao.supervisores'
import { Route as AuthenticatedConfiguracoesTiposAusenciaRouteImport } from './routes/_authenticated/configuracoes.tipos-ausencia'
import { Route as AuthenticatedConfiguracoesProjetosRouteImport } from './routes/_authenticated/configuracoes.projetos'
import { Route as AuthenticatedConfiguracoesPreferenciasRouteImport } from './routes/_authenticated/configuracoes.preferencias'
import { Route as AuthenticatedConfiguracoesEmpresasRouteImport } from './routes/_authenticated/configuracoes.empresas'
import { Route as AuthenticatedComunicacoesWhatsappRouteImport } from './routes/_authenticated/comunicacoes.whatsapp'
import { Route as AuthenticatedColaboradoresReprocessarSupervisoresRouteImport } from './routes/_authenticated/colaboradores_.reprocessar-supervisores'
import { Route as AuthenticatedColaboradoresImportarRouteImport } from './routes/_authenticated/colaboradores_.importar'
import { Route as AuthenticatedColaboradoresImportacoesRouteImport } from './routes/_authenticated/colaboradores_.importacoes'
import { Route as AuthenticatedAdministracaoVinculosManuaisRouteImport } from './routes/_authenticated/administracao.vinculos-manuais'
import { Route as AuthenticatedAdministracaoPermissoesRouteImport } from './routes/_authenticated/administracao.permissoes'
import { Route as AuthenticatedAdministracaoPendenciasSupervisorRouteImport } from './routes/_authenticated/administracao.pendencias-supervisor'
import { Route as AuthenticatedAdministracaoInvestigacoesRouteImport } from './routes/_authenticated/administracao.investigacoes'
import { Route as AuthenticatedAdministracaoIntegridadeDadosRouteImport } from './routes/_authenticated/administracao.integridade-dados'
import { Route as AuthenticatedAdministracaoHistoricoSenhasRouteImport } from './routes/_authenticated/administracao.historico-senhas'
import { Route as AuthenticatedAdministracaoGovernancaExclusoesRouteImport } from './routes/_authenticated/administracao.governanca-exclusoes'
import { Route as AuthenticatedAdministracaoCoordenacaoRouteImport } from './routes/_authenticated/administracao.coordenacao'
import { Route as AuthenticatedAdministracaoAuditoriaForenseRouteImport } from './routes/_authenticated/administracao.auditoria-forense'
import { Route as AuthenticatedAdminHardeningRouteImport } from './routes/_authenticated/admin.hardening'
import { Route as AuthenticatedComunicacoesWhatsappIndexRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.index'
import { Route as ApiPublicHooksProcessWhatsappOutboxRouteImport } from './routes/api/public/hooks/process-whatsapp-outbox'
import { Route as ApiPublicHooksEvolutionWhatsappWebhookRouteImport } from './routes/api/public/hooks/evolution-whatsapp-webhook'
import { Route as AuthenticatedUsuariosIdPermissoesRouteImport } from './routes/_authenticated/usuarios.$id.permissoes'
import { Route as AuthenticatedInteligenciaColaboradoresColaboradorIdRouteImport } from './routes/_authenticated/inteligencia.colaboradores.$colaboradorId'
import { Route as AuthenticatedConfiguracoesProjetosImportarRouteImport } from './routes/_authenticated/configuracoes.projetos_.importar'
import { Route as AuthenticatedConfiguracoesProjetosConsolidarRouteImport } from './routes/_authenticated/configuracoes.projetos_.consolidar'
import { Route as AuthenticatedComunicacoesWhatsappTstDestinatariosRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.tst-destinatarios'
import { Route as AuthenticatedComunicacoesWhatsappTestesRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.testes'
import { Route as AuthenticatedComunicacoesWhatsappOutboxRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.outbox'
import { Route as AuthenticatedComunicacoesWhatsappHealthRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.health'
import { Route as AuthenticatedComunicacoesWhatsappExecucoesRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.execucoes'
import { Route as AuthenticatedComunicacoesWhatsappDeadLetterRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.dead-letter'
import { Route as AuthenticatedComunicacoesWhatsappConfiguracaoRouteImport } from './routes/_authenticated/comunicacoes.whatsapp.configuracao'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNovaSenhaRoute = AuthNovaSenhaRouteImport.update({
  id: '/auth_/nova-senha',
  path: '/auth/nova-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessamentoRoute =
  AuthenticatedProcessamentoRouteImport.update({
    id: '/processamento',
    path: '/processamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosAcaoRoute = AuthenticatedPlanosAcaoRouteImport.update({
  id: '/planos-acao',
  path: '/planos-acao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRhRoute = AuthenticatedPainelRhRouteImport.update({
  id: '/painel-rh',
  path: '/painel-rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacaoAssistidaRoute =
  AuthenticatedOperacaoAssistidaRouteImport.update({
    id: '/operacao-assistida',
    path: '/operacao-assistida',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasPontoRoute =
  AuthenticatedOcorrenciasPontoRouteImport.update({
    id: '/ocorrencias-ponto',
    path: '/ocorrencias-ponto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObservabilidadeRoute =
  AuthenticatedObservabilidadeRouteImport.update({
    id: '/observabilidade',
    path: '/observabilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaAusenciaRoute =
  AuthenticatedNovaAusenciaRouteImport.update({
    id: '/nova-ausencia',
    path: '/nova-ausencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInteligenciaRoute =
  AuthenticatedInteligenciaRouteImport.update({
    id: '/inteligencia',
    path: '/inteligencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomologacaoRoute =
  AuthenticatedHomologacaoRouteImport.update({
    id: '/homologacao',
    path: '/homologacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentacaoRoute =
  AuthenticatedDocumentacaoRouteImport.update({
    id: '/documentacao',
    path: '/documentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeployRoute = AuthenticatedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardExecutivoRoute =
  AuthenticatedDashboardExecutivoRouteImport.update({
    id: '/dashboard-executivo',
    path: '/dashboard-executivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacoesRoute =
  AuthenticatedComunicacoesRouteImport.update({
    id: '/comunicacoes',
    path: '/comunicacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBiExecutivoRoute =
  AuthenticatedBiExecutivoRouteImport.update({
    id: '/bi-executivo',
    path: '/bi-executivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunicacoesIndexRoute =
  AuthenticatedComunicacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComunicacoesRoute,
  } as any)
const AuthenticatedInteligenciaSupervisoresRoute =
  AuthenticatedInteligenciaSupervisoresRouteImport.update({
    id: '/supervisores',
    path: '/supervisores',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedInteligenciaQualidadeRoute =
  AuthenticatedInteligenciaQualidadeRouteImport.update({
    id: '/qualidade',
    path: '/qualidade',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedInteligenciaGovernancaRoute =
  AuthenticatedInteligenciaGovernancaRouteImport.update({
    id: '/governanca',
    path: '/governanca',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedInteligenciaDashboardRoute =
  AuthenticatedInteligenciaDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedInteligenciaConfiguracaoRoute =
  AuthenticatedInteligenciaConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedInteligenciaAlertasRoute =
  AuthenticatedInteligenciaAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedCoordenacaoSupervisoresRoute =
  AuthenticatedCoordenacaoSupervisoresRouteImport.update({
    id: '/coordenacao/supervisores',
    path: '/coordenacao/supervisores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesTiposAusenciaRoute =
  AuthenticatedConfiguracoesTiposAusenciaRouteImport.update({
    id: '/tipos-ausencia',
    path: '/tipos-ausencia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesProjetosRoute =
  AuthenticatedConfiguracoesProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesPreferenciasRoute =
  AuthenticatedConfiguracoesPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesEmpresasRoute =
  AuthenticatedConfiguracoesEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappRoute =
  AuthenticatedComunicacoesWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedComunicacoesRoute,
  } as any)
const AuthenticatedColaboradoresReprocessarSupervisoresRoute =
  AuthenticatedColaboradoresReprocessarSupervisoresRouteImport.update({
    id: '/colaboradores_/reprocessar-supervisores',
    path: '/colaboradores/reprocessar-supervisores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresImportarRoute =
  AuthenticatedColaboradoresImportarRouteImport.update({
    id: '/colaboradores_/importar',
    path: '/colaboradores/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresImportacoesRoute =
  AuthenticatedColaboradoresImportacoesRouteImport.update({
    id: '/colaboradores_/importacoes',
    path: '/colaboradores/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoVinculosManuaisRoute =
  AuthenticatedAdministracaoVinculosManuaisRouteImport.update({
    id: '/administracao/vinculos-manuais',
    path: '/administracao/vinculos-manuais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoPermissoesRoute =
  AuthenticatedAdministracaoPermissoesRouteImport.update({
    id: '/administracao/permissoes',
    path: '/administracao/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoPendenciasSupervisorRoute =
  AuthenticatedAdministracaoPendenciasSupervisorRouteImport.update({
    id: '/administracao/pendencias-supervisor',
    path: '/administracao/pendencias-supervisor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoInvestigacoesRoute =
  AuthenticatedAdministracaoInvestigacoesRouteImport.update({
    id: '/administracao/investigacoes',
    path: '/administracao/investigacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoIntegridadeDadosRoute =
  AuthenticatedAdministracaoIntegridadeDadosRouteImport.update({
    id: '/administracao/integridade-dados',
    path: '/administracao/integridade-dados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoHistoricoSenhasRoute =
  AuthenticatedAdministracaoHistoricoSenhasRouteImport.update({
    id: '/administracao/historico-senhas',
    path: '/administracao/historico-senhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoGovernancaExclusoesRoute =
  AuthenticatedAdministracaoGovernancaExclusoesRouteImport.update({
    id: '/administracao/governanca-exclusoes',
    path: '/administracao/governanca-exclusoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoCoordenacaoRoute =
  AuthenticatedAdministracaoCoordenacaoRouteImport.update({
    id: '/administracao/coordenacao',
    path: '/administracao/coordenacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdministracaoAuditoriaForenseRoute =
  AuthenticatedAdministracaoAuditoriaForenseRouteImport.update({
    id: '/administracao/auditoria-forense',
    path: '/administracao/auditoria-forense',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHardeningRoute =
  AuthenticatedAdminHardeningRouteImport.update({
    id: '/admin/hardening',
    path: '/admin/hardening',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappIndexRoute =
  AuthenticatedComunicacoesWhatsappIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const ApiPublicHooksProcessWhatsappOutboxRoute =
  ApiPublicHooksProcessWhatsappOutboxRouteImport.update({
    id: '/api/public/hooks/process-whatsapp-outbox',
    path: '/api/public/hooks/process-whatsapp-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEvolutionWhatsappWebhookRoute =
  ApiPublicHooksEvolutionWhatsappWebhookRouteImport.update({
    id: '/api/public/hooks/evolution-whatsapp-webhook',
    path: '/api/public/hooks/evolution-whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsuariosIdPermissoesRoute =
  AuthenticatedUsuariosIdPermissoesRouteImport.update({
    id: '/$id/permissoes',
    path: '/$id/permissoes',
    getParentRoute: () => AuthenticatedUsuariosRoute,
  } as any)
const AuthenticatedInteligenciaColaboradoresColaboradorIdRoute =
  AuthenticatedInteligenciaColaboradoresColaboradorIdRouteImport.update({
    id: '/colaboradores/$colaboradorId',
    path: '/colaboradores/$colaboradorId',
    getParentRoute: () => AuthenticatedInteligenciaRoute,
  } as any)
const AuthenticatedConfiguracoesProjetosImportarRoute =
  AuthenticatedConfiguracoesProjetosImportarRouteImport.update({
    id: '/projetos_/importar',
    path: '/projetos/importar',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesProjetosConsolidarRoute =
  AuthenticatedConfiguracoesProjetosConsolidarRouteImport.update({
    id: '/projetos_/consolidar',
    path: '/projetos/consolidar',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappTstDestinatariosRoute =
  AuthenticatedComunicacoesWhatsappTstDestinatariosRouteImport.update({
    id: '/tst-destinatarios',
    path: '/tst-destinatarios',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappTestesRoute =
  AuthenticatedComunicacoesWhatsappTestesRouteImport.update({
    id: '/testes',
    path: '/testes',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappOutboxRoute =
  AuthenticatedComunicacoesWhatsappOutboxRouteImport.update({
    id: '/outbox',
    path: '/outbox',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappHealthRoute =
  AuthenticatedComunicacoesWhatsappHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappExecucoesRoute =
  AuthenticatedComunicacoesWhatsappExecucoesRouteImport.update({
    id: '/execucoes',
    path: '/execucoes',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappDeadLetterRoute =
  AuthenticatedComunicacoesWhatsappDeadLetterRouteImport.update({
    id: '/dead-letter',
    path: '/dead-letter',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)
const AuthenticatedComunicacoesWhatsappConfiguracaoRoute =
  AuthenticatedComunicacoesWhatsappConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedComunicacoesWhatsappRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/bi-executivo': typeof AuthenticatedBiExecutivoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/comunicacoes': typeof AuthenticatedComunicacoesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-executivo': typeof AuthenticatedDashboardExecutivoRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/ocorrencias-ponto': typeof AuthenticatedOcorrenciasPontoRoute
  '/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/painel-rh': typeof AuthenticatedPainelRhRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/processamento': typeof AuthenticatedProcessamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/admin/hardening': typeof AuthenticatedAdminHardeningRoute
  '/administracao/auditoria-forense': typeof AuthenticatedAdministracaoAuditoriaForenseRoute
  '/administracao/coordenacao': typeof AuthenticatedAdministracaoCoordenacaoRoute
  '/administracao/governanca-exclusoes': typeof AuthenticatedAdministracaoGovernancaExclusoesRoute
  '/administracao/historico-senhas': typeof AuthenticatedAdministracaoHistoricoSenhasRoute
  '/administracao/integridade-dados': typeof AuthenticatedAdministracaoIntegridadeDadosRoute
  '/administracao/investigacoes': typeof AuthenticatedAdministracaoInvestigacoesRoute
  '/administracao/pendencias-supervisor': typeof AuthenticatedAdministracaoPendenciasSupervisorRoute
  '/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/administracao/vinculos-manuais': typeof AuthenticatedAdministracaoVinculosManuaisRoute
  '/colaboradores/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/colaboradores/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/colaboradores/reprocessar-supervisores': typeof AuthenticatedColaboradoresReprocessarSupervisoresRoute
  '/comunicacoes/whatsapp': typeof AuthenticatedComunicacoesWhatsappRouteWithChildren
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/configuracoes/preferencias': typeof AuthenticatedConfiguracoesPreferenciasRoute
  '/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
  '/coordenacao/supervisores': typeof AuthenticatedCoordenacaoSupervisoresRoute
  '/inteligencia/alertas': typeof AuthenticatedInteligenciaAlertasRoute
  '/inteligencia/configuracao': typeof AuthenticatedInteligenciaConfiguracaoRoute
  '/inteligencia/dashboard': typeof AuthenticatedInteligenciaDashboardRoute
  '/inteligencia/governanca': typeof AuthenticatedInteligenciaGovernancaRoute
  '/inteligencia/qualidade': typeof AuthenticatedInteligenciaQualidadeRoute
  '/inteligencia/supervisores': typeof AuthenticatedInteligenciaSupervisoresRoute
  '/comunicacoes/': typeof AuthenticatedComunicacoesIndexRoute
  '/comunicacoes/whatsapp/configuracao': typeof AuthenticatedComunicacoesWhatsappConfiguracaoRoute
  '/comunicacoes/whatsapp/dead-letter': typeof AuthenticatedComunicacoesWhatsappDeadLetterRoute
  '/comunicacoes/whatsapp/execucoes': typeof AuthenticatedComunicacoesWhatsappExecucoesRoute
  '/comunicacoes/whatsapp/health': typeof AuthenticatedComunicacoesWhatsappHealthRoute
  '/comunicacoes/whatsapp/outbox': typeof AuthenticatedComunicacoesWhatsappOutboxRoute
  '/comunicacoes/whatsapp/testes': typeof AuthenticatedComunicacoesWhatsappTestesRoute
  '/comunicacoes/whatsapp/tst-destinatarios': typeof AuthenticatedComunicacoesWhatsappTstDestinatariosRoute
  '/configuracoes/projetos/consolidar': typeof AuthenticatedConfiguracoesProjetosConsolidarRoute
  '/configuracoes/projetos/importar': typeof AuthenticatedConfiguracoesProjetosImportarRoute
  '/inteligencia/colaboradores/$colaboradorId': typeof AuthenticatedInteligenciaColaboradoresColaboradorIdRoute
  '/usuarios/$id/permissoes': typeof AuthenticatedUsuariosIdPermissoesRoute
  '/api/public/hooks/evolution-whatsapp-webhook': typeof ApiPublicHooksEvolutionWhatsappWebhookRoute
  '/api/public/hooks/process-whatsapp-outbox': typeof ApiPublicHooksProcessWhatsappOutboxRoute
  '/comunicacoes/whatsapp/': typeof AuthenticatedComunicacoesWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/bi-executivo': typeof AuthenticatedBiExecutivoRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboard-executivo': typeof AuthenticatedDashboardExecutivoRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/inteligencia': typeof AuthenticatedInteligenciaRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/ocorrencias-ponto': typeof AuthenticatedOcorrenciasPontoRoute
  '/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/painel-rh': typeof AuthenticatedPainelRhRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/processamento': typeof AuthenticatedProcessamentoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/admin/hardening': typeof AuthenticatedAdminHardeningRoute
  '/administracao/auditoria-forense': typeof AuthenticatedAdministracaoAuditoriaForenseRoute
  '/administracao/coordenacao': typeof AuthenticatedAdministracaoCoordenacaoRoute
  '/administracao/governanca-exclusoes': typeof AuthenticatedAdministracaoGovernancaExclusoesRoute
  '/administracao/historico-senhas': typeof AuthenticatedAdministracaoHistoricoSenhasRoute
  '/administracao/integridade-dados': typeof AuthenticatedAdministracaoIntegridadeDadosRoute
  '/administracao/investigacoes': typeof AuthenticatedAdministracaoInvestigacoesRoute
  '/administracao/pendencias-supervisor': typeof AuthenticatedAdministracaoPendenciasSupervisorRoute
  '/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/administracao/vinculos-manuais': typeof AuthenticatedAdministracaoVinculosManuaisRoute
  '/colaboradores/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/colaboradores/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/colaboradores/reprocessar-supervisores': typeof AuthenticatedColaboradoresReprocessarSupervisoresRoute
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/configuracoes/preferencias': typeof AuthenticatedConfiguracoesPreferenciasRoute
  '/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
  '/coordenacao/supervisores': typeof AuthenticatedCoordenacaoSupervisoresRoute
  '/inteligencia/alertas': typeof AuthenticatedInteligenciaAlertasRoute
  '/inteligencia/configuracao': typeof AuthenticatedInteligenciaConfiguracaoRoute
  '/inteligencia/dashboard': typeof AuthenticatedInteligenciaDashboardRoute
  '/inteligencia/governanca': typeof AuthenticatedInteligenciaGovernancaRoute
  '/inteligencia/qualidade': typeof AuthenticatedInteligenciaQualidadeRoute
  '/inteligencia/supervisores': typeof AuthenticatedInteligenciaSupervisoresRoute
  '/comunicacoes': typeof AuthenticatedComunicacoesIndexRoute
  '/comunicacoes/whatsapp/configuracao': typeof AuthenticatedComunicacoesWhatsappConfiguracaoRoute
  '/comunicacoes/whatsapp/dead-letter': typeof AuthenticatedComunicacoesWhatsappDeadLetterRoute
  '/comunicacoes/whatsapp/execucoes': typeof AuthenticatedComunicacoesWhatsappExecucoesRoute
  '/comunicacoes/whatsapp/health': typeof AuthenticatedComunicacoesWhatsappHealthRoute
  '/comunicacoes/whatsapp/outbox': typeof AuthenticatedComunicacoesWhatsappOutboxRoute
  '/comunicacoes/whatsapp/testes': typeof AuthenticatedComunicacoesWhatsappTestesRoute
  '/comunicacoes/whatsapp/tst-destinatarios': typeof AuthenticatedComunicacoesWhatsappTstDestinatariosRoute
  '/configuracoes/projetos/consolidar': typeof AuthenticatedConfiguracoesProjetosConsolidarRoute
  '/configuracoes/projetos/importar': typeof AuthenticatedConfiguracoesProjetosImportarRoute
  '/inteligencia/colaboradores/$colaboradorId': typeof AuthenticatedInteligenciaColaboradoresColaboradorIdRoute
  '/usuarios/$id/permissoes': typeof AuthenticatedUsuariosIdPermissoesRoute
  '/api/public/hooks/evolution-whatsapp-webhook': typeof ApiPublicHooksEvolutionWhatsappWebhookRoute
  '/api/public/hooks/process-whatsapp-outbox': typeof ApiPublicHooksProcessWhatsappOutboxRoute
  '/comunicacoes/whatsapp': typeof AuthenticatedComunicacoesWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/bi-executivo': typeof AuthenticatedBiExecutivoRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/comunicacoes': typeof AuthenticatedComunicacoesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboard-executivo': typeof AuthenticatedDashboardExecutivoRoute
  '/_authenticated/deploy': typeof AuthenticatedDeployRoute
  '/_authenticated/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/homologacao': typeof AuthenticatedHomologacaoRoute
  '/_authenticated/inteligencia': typeof AuthenticatedInteligenciaRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/_authenticated/observabilidade': typeof AuthenticatedObservabilidadeRoute
  '/_authenticated/ocorrencias-ponto': typeof AuthenticatedOcorrenciasPontoRoute
  '/_authenticated/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRoute
  '/_authenticated/painel-rh': typeof AuthenticatedPainelRhRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos-acao': typeof AuthenticatedPlanosAcaoRoute
  '/_authenticated/processamento': typeof AuthenticatedProcessamentoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/auth_/nova-senha': typeof AuthNovaSenhaRoute
  '/_authenticated/admin/hardening': typeof AuthenticatedAdminHardeningRoute
  '/_authenticated/administracao/auditoria-forense': typeof AuthenticatedAdministracaoAuditoriaForenseRoute
  '/_authenticated/administracao/coordenacao': typeof AuthenticatedAdministracaoCoordenacaoRoute
  '/_authenticated/administracao/governanca-exclusoes': typeof AuthenticatedAdministracaoGovernancaExclusoesRoute
  '/_authenticated/administracao/historico-senhas': typeof AuthenticatedAdministracaoHistoricoSenhasRoute
  '/_authenticated/administracao/integridade-dados': typeof AuthenticatedAdministracaoIntegridadeDadosRoute
  '/_authenticated/administracao/investigacoes': typeof AuthenticatedAdministracaoInvestigacoesRoute
  '/_authenticated/administracao/pendencias-supervisor': typeof AuthenticatedAdministracaoPendenciasSupervisorRoute
  '/_authenticated/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/_authenticated/administracao/vinculos-manuais': typeof AuthenticatedAdministracaoVinculosManuaisRoute
  '/_authenticated/colaboradores_/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/_authenticated/colaboradores_/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/_authenticated/colaboradores_/reprocessar-supervisores': typeof AuthenticatedColaboradoresReprocessarSupervisoresRoute
  '/_authenticated/comunicacoes/whatsapp': typeof AuthenticatedComunicacoesWhatsappRouteWithChildren
  '/_authenticated/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/_authenticated/configuracoes/preferencias': typeof AuthenticatedConfiguracoesPreferenciasRoute
  '/_authenticated/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/_authenticated/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
  '/_authenticated/coordenacao/supervisores': typeof AuthenticatedCoordenacaoSupervisoresRoute
  '/_authenticated/inteligencia/alertas': typeof AuthenticatedInteligenciaAlertasRoute
  '/_authenticated/inteligencia/configuracao': typeof AuthenticatedInteligenciaConfiguracaoRoute
  '/_authenticated/inteligencia/dashboard': typeof AuthenticatedInteligenciaDashboardRoute
  '/_authenticated/inteligencia/governanca': typeof AuthenticatedInteligenciaGovernancaRoute
  '/_authenticated/inteligencia/qualidade': typeof AuthenticatedInteligenciaQualidadeRoute
  '/_authenticated/inteligencia/supervisores': typeof AuthenticatedInteligenciaSupervisoresRoute
  '/_authenticated/comunicacoes/': typeof AuthenticatedComunicacoesIndexRoute
  '/_authenticated/comunicacoes/whatsapp/configuracao': typeof AuthenticatedComunicacoesWhatsappConfiguracaoRoute
  '/_authenticated/comunicacoes/whatsapp/dead-letter': typeof AuthenticatedComunicacoesWhatsappDeadLetterRoute
  '/_authenticated/comunicacoes/whatsapp/execucoes': typeof AuthenticatedComunicacoesWhatsappExecucoesRoute
  '/_authenticated/comunicacoes/whatsapp/health': typeof AuthenticatedComunicacoesWhatsappHealthRoute
  '/_authenticated/comunicacoes/whatsapp/outbox': typeof AuthenticatedComunicacoesWhatsappOutboxRoute
  '/_authenticated/comunicacoes/whatsapp/testes': typeof AuthenticatedComunicacoesWhatsappTestesRoute
  '/_authenticated/comunicacoes/whatsapp/tst-destinatarios': typeof AuthenticatedComunicacoesWhatsappTstDestinatariosRoute
  '/_authenticated/configuracoes/projetos_/consolidar': typeof AuthenticatedConfiguracoesProjetosConsolidarRoute
  '/_authenticated/configuracoes/projetos_/importar': typeof AuthenticatedConfiguracoesProjetosImportarRoute
  '/_authenticated/inteligencia/colaboradores/$colaboradorId': typeof AuthenticatedInteligenciaColaboradoresColaboradorIdRoute
  '/_authenticated/usuarios/$id/permissoes': typeof AuthenticatedUsuariosIdPermissoesRoute
  '/api/public/hooks/evolution-whatsapp-webhook': typeof ApiPublicHooksEvolutionWhatsappWebhookRoute
  '/api/public/hooks/process-whatsapp-outbox': typeof ApiPublicHooksProcessWhatsappOutboxRoute
  '/_authenticated/comunicacoes/whatsapp/': typeof AuthenticatedComunicacoesWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acessos'
    | '/alertas'
    | '/assistente'
    | '/auditoria'
    | '/ausencias'
    | '/bi-executivo'
    | '/colaboradores'
    | '/comunicacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboard-executivo'
    | '/deploy'
    | '/documentacao'
    | '/historico'
    | '/homologacao'
    | '/inteligencia'
    | '/notificacoes'
    | '/nova-ausencia'
    | '/observabilidade'
    | '/ocorrencias-ponto'
    | '/operacao-assistida'
    | '/operacoes'
    | '/painel-rh'
    | '/perfil'
    | '/planos-acao'
    | '/processamento'
    | '/relatorios'
    | '/roadmap'
    | '/saude'
    | '/usuarios'
    | '/auth/nova-senha'
    | '/admin/hardening'
    | '/administracao/auditoria-forense'
    | '/administracao/coordenacao'
    | '/administracao/governanca-exclusoes'
    | '/administracao/historico-senhas'
    | '/administracao/integridade-dados'
    | '/administracao/investigacoes'
    | '/administracao/pendencias-supervisor'
    | '/administracao/permissoes'
    | '/administracao/vinculos-manuais'
    | '/colaboradores/importacoes'
    | '/colaboradores/importar'
    | '/colaboradores/reprocessar-supervisores'
    | '/comunicacoes/whatsapp'
    | '/configuracoes/empresas'
    | '/configuracoes/preferencias'
    | '/configuracoes/projetos'
    | '/configuracoes/tipos-ausencia'
    | '/coordenacao/supervisores'
    | '/inteligencia/alertas'
    | '/inteligencia/configuracao'
    | '/inteligencia/dashboard'
    | '/inteligencia/governanca'
    | '/inteligencia/qualidade'
    | '/inteligencia/supervisores'
    | '/comunicacoes/'
    | '/comunicacoes/whatsapp/configuracao'
    | '/comunicacoes/whatsapp/dead-letter'
    | '/comunicacoes/whatsapp/execucoes'
    | '/comunicacoes/whatsapp/health'
    | '/comunicacoes/whatsapp/outbox'
    | '/comunicacoes/whatsapp/testes'
    | '/comunicacoes/whatsapp/tst-destinatarios'
    | '/configuracoes/projetos/consolidar'
    | '/configuracoes/projetos/importar'
    | '/inteligencia/colaboradores/$colaboradorId'
    | '/usuarios/$id/permissoes'
    | '/api/public/hooks/evolution-whatsapp-webhook'
    | '/api/public/hooks/process-whatsapp-outbox'
    | '/comunicacoes/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/acessos'
    | '/alertas'
    | '/assistente'
    | '/auditoria'
    | '/ausencias'
    | '/bi-executivo'
    | '/colaboradores'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboard-executivo'
    | '/deploy'
    | '/documentacao'
    | '/historico'
    | '/homologacao'
    | '/inteligencia'
    | '/notificacoes'
    | '/nova-ausencia'
    | '/observabilidade'
    | '/ocorrencias-ponto'
    | '/operacao-assistida'
    | '/operacoes'
    | '/painel-rh'
    | '/perfil'
    | '/planos-acao'
    | '/processamento'
    | '/relatorios'
    | '/roadmap'
    | '/saude'
    | '/usuarios'
    | '/auth/nova-senha'
    | '/admin/hardening'
    | '/administracao/auditoria-forense'
    | '/administracao/coordenacao'
    | '/administracao/governanca-exclusoes'
    | '/administracao/historico-senhas'
    | '/administracao/integridade-dados'
    | '/administracao/investigacoes'
    | '/administracao/pendencias-supervisor'
    | '/administracao/permissoes'
    | '/administracao/vinculos-manuais'
    | '/colaboradores/importacoes'
    | '/colaboradores/importar'
    | '/colaboradores/reprocessar-supervisores'
    | '/configuracoes/empresas'
    | '/configuracoes/preferencias'
    | '/configuracoes/projetos'
    | '/configuracoes/tipos-ausencia'
    | '/coordenacao/supervisores'
    | '/inteligencia/alertas'
    | '/inteligencia/configuracao'
    | '/inteligencia/dashboard'
    | '/inteligencia/governanca'
    | '/inteligencia/qualidade'
    | '/inteligencia/supervisores'
    | '/comunicacoes'
    | '/comunicacoes/whatsapp/configuracao'
    | '/comunicacoes/whatsapp/dead-letter'
    | '/comunicacoes/whatsapp/execucoes'
    | '/comunicacoes/whatsapp/health'
    | '/comunicacoes/whatsapp/outbox'
    | '/comunicacoes/whatsapp/testes'
    | '/comunicacoes/whatsapp/tst-destinatarios'
    | '/configuracoes/projetos/consolidar'
    | '/configuracoes/projetos/importar'
    | '/inteligencia/colaboradores/$colaboradorId'
    | '/usuarios/$id/permissoes'
    | '/api/public/hooks/evolution-whatsapp-webhook'
    | '/api/public/hooks/process-whatsapp-outbox'
    | '/comunicacoes/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/acessos'
    | '/_authenticated/alertas'
    | '/_authenticated/assistente'
    | '/_authenticated/auditoria'
    | '/_authenticated/ausencias'
    | '/_authenticated/bi-executivo'
    | '/_authenticated/colaboradores'
    | '/_authenticated/comunicacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-executivo'
    | '/_authenticated/deploy'
    | '/_authenticated/documentacao'
    | '/_authenticated/historico'
    | '/_authenticated/homologacao'
    | '/_authenticated/inteligencia'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-ausencia'
    | '/_authenticated/observabilidade'
    | '/_authenticated/ocorrencias-ponto'
    | '/_authenticated/operacao-assistida'
    | '/_authenticated/operacoes'
    | '/_authenticated/painel-rh'
    | '/_authenticated/perfil'
    | '/_authenticated/planos-acao'
    | '/_authenticated/processamento'
    | '/_authenticated/relatorios'
    | '/_authenticated/roadmap'
    | '/_authenticated/saude'
    | '/_authenticated/usuarios'
    | '/auth_/nova-senha'
    | '/_authenticated/admin/hardening'
    | '/_authenticated/administracao/auditoria-forense'
    | '/_authenticated/administracao/coordenacao'
    | '/_authenticated/administracao/governanca-exclusoes'
    | '/_authenticated/administracao/historico-senhas'
    | '/_authenticated/administracao/integridade-dados'
    | '/_authenticated/administracao/investigacoes'
    | '/_authenticated/administracao/pendencias-supervisor'
    | '/_authenticated/administracao/permissoes'
    | '/_authenticated/administracao/vinculos-manuais'
    | '/_authenticated/colaboradores_/importacoes'
    | '/_authenticated/colaboradores_/importar'
    | '/_authenticated/colaboradores_/reprocessar-supervisores'
    | '/_authenticated/comunicacoes/whatsapp'
    | '/_authenticated/configuracoes/empresas'
    | '/_authenticated/configuracoes/preferencias'
    | '/_authenticated/configuracoes/projetos'
    | '/_authenticated/configuracoes/tipos-ausencia'
    | '/_authenticated/coordenacao/supervisores'
    | '/_authenticated/inteligencia/alertas'
    | '/_authenticated/inteligencia/configuracao'
    | '/_authenticated/inteligencia/dashboard'
    | '/_authenticated/inteligencia/governanca'
    | '/_authenticated/inteligencia/qualidade'
    | '/_authenticated/inteligencia/supervisores'
    | '/_authenticated/comunicacoes/'
    | '/_authenticated/comunicacoes/whatsapp/configuracao'
    | '/_authenticated/comunicacoes/whatsapp/dead-letter'
    | '/_authenticated/comunicacoes/whatsapp/execucoes'
    | '/_authenticated/comunicacoes/whatsapp/health'
    | '/_authenticated/comunicacoes/whatsapp/outbox'
    | '/_authenticated/comunicacoes/whatsapp/testes'
    | '/_authenticated/comunicacoes/whatsapp/tst-destinatarios'
    | '/_authenticated/configuracoes/projetos_/consolidar'
    | '/_authenticated/configuracoes/projetos_/importar'
    | '/_authenticated/inteligencia/colaboradores/$colaboradorId'
    | '/_authenticated/usuarios/$id/permissoes'
    | '/api/public/hooks/evolution-whatsapp-webhook'
    | '/api/public/hooks/process-whatsapp-outbox'
    | '/_authenticated/comunicacoes/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthNovaSenhaRoute: typeof AuthNovaSenhaRoute
  ApiPublicHooksEvolutionWhatsappWebhookRoute: typeof ApiPublicHooksEvolutionWhatsappWebhookRoute
  ApiPublicHooksProcessWhatsappOutboxRoute: typeof ApiPublicHooksProcessWhatsappOutboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/nova-senha': {
      id: '/auth_/nova-senha'
      path: '/auth/nova-senha'
      fullPath: '/auth/nova-senha'
      preLoaderRoute: typeof AuthNovaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processamento': {
      id: '/_authenticated/processamento'
      path: '/processamento'
      fullPath: '/processamento'
      preLoaderRoute: typeof AuthenticatedProcessamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos-acao': {
      id: '/_authenticated/planos-acao'
      path: '/planos-acao'
      fullPath: '/planos-acao'
      preLoaderRoute: typeof AuthenticatedPlanosAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-rh': {
      id: '/_authenticated/painel-rh'
      path: '/painel-rh'
      fullPath: '/painel-rh'
      preLoaderRoute: typeof AuthenticatedPainelRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao-assistida': {
      id: '/_authenticated/operacao-assistida'
      path: '/operacao-assistida'
      fullPath: '/operacao-assistida'
      preLoaderRoute: typeof AuthenticatedOperacaoAssistidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias-ponto': {
      id: '/_authenticated/ocorrencias-ponto'
      path: '/ocorrencias-ponto'
      fullPath: '/ocorrencias-ponto'
      preLoaderRoute: typeof AuthenticatedOcorrenciasPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observabilidade': {
      id: '/_authenticated/observabilidade'
      path: '/observabilidade'
      fullPath: '/observabilidade'
      preLoaderRoute: typeof AuthenticatedObservabilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ausencia': {
      id: '/_authenticated/nova-ausencia'
      path: '/nova-ausencia'
      fullPath: '/nova-ausencia'
      preLoaderRoute: typeof AuthenticatedNovaAusenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inteligencia': {
      id: '/_authenticated/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AuthenticatedInteligenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homologacao': {
      id: '/_authenticated/homologacao'
      path: '/homologacao'
      fullPath: '/homologacao'
      preLoaderRoute: typeof AuthenticatedHomologacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentacao': {
      id: '/_authenticated/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AuthenticatedDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deploy': {
      id: '/_authenticated/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthenticatedDeployRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-executivo': {
      id: '/_authenticated/dashboard-executivo'
      path: '/dashboard-executivo'
      fullPath: '/dashboard-executivo'
      preLoaderRoute: typeof AuthenticatedDashboardExecutivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacoes': {
      id: '/_authenticated/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/comunicacoes'
      preLoaderRoute: typeof AuthenticatedComunicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi-executivo': {
      id: '/_authenticated/bi-executivo'
      path: '/bi-executivo'
      fullPath: '/bi-executivo'
      preLoaderRoute: typeof AuthenticatedBiExecutivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacoes/': {
      id: '/_authenticated/comunicacoes/'
      path: '/'
      fullPath: '/comunicacoes/'
      preLoaderRoute: typeof AuthenticatedComunicacoesIndexRouteImport
      parentRoute: typeof AuthenticatedComunicacoesRoute
    }
    '/_authenticated/inteligencia/supervisores': {
      id: '/_authenticated/inteligencia/supervisores'
      path: '/supervisores'
      fullPath: '/inteligencia/supervisores'
      preLoaderRoute: typeof AuthenticatedInteligenciaSupervisoresRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/inteligencia/qualidade': {
      id: '/_authenticated/inteligencia/qualidade'
      path: '/qualidade'
      fullPath: '/inteligencia/qualidade'
      preLoaderRoute: typeof AuthenticatedInteligenciaQualidadeRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/inteligencia/governanca': {
      id: '/_authenticated/inteligencia/governanca'
      path: '/governanca'
      fullPath: '/inteligencia/governanca'
      preLoaderRoute: typeof AuthenticatedInteligenciaGovernancaRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/inteligencia/dashboard': {
      id: '/_authenticated/inteligencia/dashboard'
      path: '/dashboard'
      fullPath: '/inteligencia/dashboard'
      preLoaderRoute: typeof AuthenticatedInteligenciaDashboardRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/inteligencia/configuracao': {
      id: '/_authenticated/inteligencia/configuracao'
      path: '/configuracao'
      fullPath: '/inteligencia/configuracao'
      preLoaderRoute: typeof AuthenticatedInteligenciaConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/inteligencia/alertas': {
      id: '/_authenticated/inteligencia/alertas'
      path: '/alertas'
      fullPath: '/inteligencia/alertas'
      preLoaderRoute: typeof AuthenticatedInteligenciaAlertasRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/coordenacao/supervisores': {
      id: '/_authenticated/coordenacao/supervisores'
      path: '/coordenacao/supervisores'
      fullPath: '/coordenacao/supervisores'
      preLoaderRoute: typeof AuthenticatedCoordenacaoSupervisoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/tipos-ausencia': {
      id: '/_authenticated/configuracoes/tipos-ausencia'
      path: '/tipos-ausencia'
      fullPath: '/configuracoes/tipos-ausencia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTiposAusenciaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/projetos': {
      id: '/_authenticated/configuracoes/projetos'
      path: '/projetos'
      fullPath: '/configuracoes/projetos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesProjetosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/preferencias': {
      id: '/_authenticated/configuracoes/preferencias'
      path: '/preferencias'
      fullPath: '/configuracoes/preferencias'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPreferenciasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/empresas': {
      id: '/_authenticated/configuracoes/empresas'
      path: '/empresas'
      fullPath: '/configuracoes/empresas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmpresasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/comunicacoes/whatsapp': {
      id: '/_authenticated/comunicacoes/whatsapp'
      path: '/whatsapp'
      fullPath: '/comunicacoes/whatsapp'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappRouteImport
      parentRoute: typeof AuthenticatedComunicacoesRoute
    }
    '/_authenticated/colaboradores_/reprocessar-supervisores': {
      id: '/_authenticated/colaboradores_/reprocessar-supervisores'
      path: '/colaboradores/reprocessar-supervisores'
      fullPath: '/colaboradores/reprocessar-supervisores'
      preLoaderRoute: typeof AuthenticatedColaboradoresReprocessarSupervisoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores_/importar': {
      id: '/_authenticated/colaboradores_/importar'
      path: '/colaboradores/importar'
      fullPath: '/colaboradores/importar'
      preLoaderRoute: typeof AuthenticatedColaboradoresImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores_/importacoes': {
      id: '/_authenticated/colaboradores_/importacoes'
      path: '/colaboradores/importacoes'
      fullPath: '/colaboradores/importacoes'
      preLoaderRoute: typeof AuthenticatedColaboradoresImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/vinculos-manuais': {
      id: '/_authenticated/administracao/vinculos-manuais'
      path: '/administracao/vinculos-manuais'
      fullPath: '/administracao/vinculos-manuais'
      preLoaderRoute: typeof AuthenticatedAdministracaoVinculosManuaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/permissoes': {
      id: '/_authenticated/administracao/permissoes'
      path: '/administracao/permissoes'
      fullPath: '/administracao/permissoes'
      preLoaderRoute: typeof AuthenticatedAdministracaoPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/pendencias-supervisor': {
      id: '/_authenticated/administracao/pendencias-supervisor'
      path: '/administracao/pendencias-supervisor'
      fullPath: '/administracao/pendencias-supervisor'
      preLoaderRoute: typeof AuthenticatedAdministracaoPendenciasSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/investigacoes': {
      id: '/_authenticated/administracao/investigacoes'
      path: '/administracao/investigacoes'
      fullPath: '/administracao/investigacoes'
      preLoaderRoute: typeof AuthenticatedAdministracaoInvestigacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/integridade-dados': {
      id: '/_authenticated/administracao/integridade-dados'
      path: '/administracao/integridade-dados'
      fullPath: '/administracao/integridade-dados'
      preLoaderRoute: typeof AuthenticatedAdministracaoIntegridadeDadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/historico-senhas': {
      id: '/_authenticated/administracao/historico-senhas'
      path: '/administracao/historico-senhas'
      fullPath: '/administracao/historico-senhas'
      preLoaderRoute: typeof AuthenticatedAdministracaoHistoricoSenhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/governanca-exclusoes': {
      id: '/_authenticated/administracao/governanca-exclusoes'
      path: '/administracao/governanca-exclusoes'
      fullPath: '/administracao/governanca-exclusoes'
      preLoaderRoute: typeof AuthenticatedAdministracaoGovernancaExclusoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/coordenacao': {
      id: '/_authenticated/administracao/coordenacao'
      path: '/administracao/coordenacao'
      fullPath: '/administracao/coordenacao'
      preLoaderRoute: typeof AuthenticatedAdministracaoCoordenacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao/auditoria-forense': {
      id: '/_authenticated/administracao/auditoria-forense'
      path: '/administracao/auditoria-forense'
      fullPath: '/administracao/auditoria-forense'
      preLoaderRoute: typeof AuthenticatedAdministracaoAuditoriaForenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hardening': {
      id: '/_authenticated/admin/hardening'
      path: '/admin/hardening'
      fullPath: '/admin/hardening'
      preLoaderRoute: typeof AuthenticatedAdminHardeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacoes/whatsapp/': {
      id: '/_authenticated/comunicacoes/whatsapp/'
      path: '/'
      fullPath: '/comunicacoes/whatsapp/'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/api/public/hooks/process-whatsapp-outbox': {
      id: '/api/public/hooks/process-whatsapp-outbox'
      path: '/api/public/hooks/process-whatsapp-outbox'
      fullPath: '/api/public/hooks/process-whatsapp-outbox'
      preLoaderRoute: typeof ApiPublicHooksProcessWhatsappOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evolution-whatsapp-webhook': {
      id: '/api/public/hooks/evolution-whatsapp-webhook'
      path: '/api/public/hooks/evolution-whatsapp-webhook'
      fullPath: '/api/public/hooks/evolution-whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicHooksEvolutionWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios/$id/permissoes': {
      id: '/_authenticated/usuarios/$id/permissoes'
      path: '/$id/permissoes'
      fullPath: '/usuarios/$id/permissoes'
      preLoaderRoute: typeof AuthenticatedUsuariosIdPermissoesRouteImport
      parentRoute: typeof AuthenticatedUsuariosRoute
    }
    '/_authenticated/inteligencia/colaboradores/$colaboradorId': {
      id: '/_authenticated/inteligencia/colaboradores/$colaboradorId'
      path: '/colaboradores/$colaboradorId'
      fullPath: '/inteligencia/colaboradores/$colaboradorId'
      preLoaderRoute: typeof AuthenticatedInteligenciaColaboradoresColaboradorIdRouteImport
      parentRoute: typeof AuthenticatedInteligenciaRoute
    }
    '/_authenticated/configuracoes/projetos_/importar': {
      id: '/_authenticated/configuracoes/projetos_/importar'
      path: '/projetos/importar'
      fullPath: '/configuracoes/projetos/importar'
      preLoaderRoute: typeof AuthenticatedConfiguracoesProjetosImportarRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/projetos_/consolidar': {
      id: '/_authenticated/configuracoes/projetos_/consolidar'
      path: '/projetos/consolidar'
      fullPath: '/configuracoes/projetos/consolidar'
      preLoaderRoute: typeof AuthenticatedConfiguracoesProjetosConsolidarRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/comunicacoes/whatsapp/tst-destinatarios': {
      id: '/_authenticated/comunicacoes/whatsapp/tst-destinatarios'
      path: '/tst-destinatarios'
      fullPath: '/comunicacoes/whatsapp/tst-destinatarios'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappTstDestinatariosRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/testes': {
      id: '/_authenticated/comunicacoes/whatsapp/testes'
      path: '/testes'
      fullPath: '/comunicacoes/whatsapp/testes'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappTestesRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/outbox': {
      id: '/_authenticated/comunicacoes/whatsapp/outbox'
      path: '/outbox'
      fullPath: '/comunicacoes/whatsapp/outbox'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappOutboxRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/health': {
      id: '/_authenticated/comunicacoes/whatsapp/health'
      path: '/health'
      fullPath: '/comunicacoes/whatsapp/health'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappHealthRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/execucoes': {
      id: '/_authenticated/comunicacoes/whatsapp/execucoes'
      path: '/execucoes'
      fullPath: '/comunicacoes/whatsapp/execucoes'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappExecucoesRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/dead-letter': {
      id: '/_authenticated/comunicacoes/whatsapp/dead-letter'
      path: '/dead-letter'
      fullPath: '/comunicacoes/whatsapp/dead-letter'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappDeadLetterRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
    '/_authenticated/comunicacoes/whatsapp/configuracao': {
      id: '/_authenticated/comunicacoes/whatsapp/configuracao'
      path: '/configuracao'
      fullPath: '/comunicacoes/whatsapp/configuracao'
      preLoaderRoute: typeof AuthenticatedComunicacoesWhatsappConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedComunicacoesWhatsappRoute
    }
  }
}

interface AuthenticatedComunicacoesWhatsappRouteChildren {
  AuthenticatedComunicacoesWhatsappConfiguracaoRoute: typeof AuthenticatedComunicacoesWhatsappConfiguracaoRoute
  AuthenticatedComunicacoesWhatsappDeadLetterRoute: typeof AuthenticatedComunicacoesWhatsappDeadLetterRoute
  AuthenticatedComunicacoesWhatsappExecucoesRoute: typeof AuthenticatedComunicacoesWhatsappExecucoesRoute
  AuthenticatedComunicacoesWhatsappHealthRoute: typeof AuthenticatedComunicacoesWhatsappHealthRoute
  AuthenticatedComunicacoesWhatsappOutboxRoute: typeof AuthenticatedComunicacoesWhatsappOutboxRoute
  AuthenticatedComunicacoesWhatsappTestesRoute: typeof AuthenticatedComunicacoesWhatsappTestesRoute
  AuthenticatedComunicacoesWhatsappTstDestinatariosRoute: typeof AuthenticatedComunicacoesWhatsappTstDestinatariosRoute
  AuthenticatedComunicacoesWhatsappIndexRoute: typeof AuthenticatedComunicacoesWhatsappIndexRoute
}

const AuthenticatedComunicacoesWhatsappRouteChildren: AuthenticatedComunicacoesWhatsappRouteChildren =
  {
    AuthenticatedComunicacoesWhatsappConfiguracaoRoute:
      AuthenticatedComunicacoesWhatsappConfiguracaoRoute,
    AuthenticatedComunicacoesWhatsappDeadLetterRoute:
      AuthenticatedComunicacoesWhatsappDeadLetterRoute,
    AuthenticatedComunicacoesWhatsappExecucoesRoute:
      AuthenticatedComunicacoesWhatsappExecucoesRoute,
    AuthenticatedComunicacoesWhatsappHealthRoute:
      AuthenticatedComunicacoesWhatsappHealthRoute,
    AuthenticatedComunicacoesWhatsappOutboxRoute:
      AuthenticatedComunicacoesWhatsappOutboxRoute,
    AuthenticatedComunicacoesWhatsappTestesRoute:
      AuthenticatedComunicacoesWhatsappTestesRoute,
    AuthenticatedComunicacoesWhatsappTstDestinatariosRoute:
      AuthenticatedComunicacoesWhatsappTstDestinatariosRoute,
    AuthenticatedComunicacoesWhatsappIndexRoute:
      AuthenticatedComunicacoesWhatsappIndexRoute,
  }

const AuthenticatedComunicacoesWhatsappRouteWithChildren =
  AuthenticatedComunicacoesWhatsappRoute._addFileChildren(
    AuthenticatedComunicacoesWhatsappRouteChildren,
  )

interface AuthenticatedComunicacoesRouteChildren {
  AuthenticatedComunicacoesWhatsappRoute: typeof AuthenticatedComunicacoesWhatsappRouteWithChildren
  AuthenticatedComunicacoesIndexRoute: typeof AuthenticatedComunicacoesIndexRoute
}

const AuthenticatedComunicacoesRouteChildren: AuthenticatedComunicacoesRouteChildren =
  {
    AuthenticatedComunicacoesWhatsappRoute:
      AuthenticatedComunicacoesWhatsappRouteWithChildren,
    AuthenticatedComunicacoesIndexRoute: AuthenticatedComunicacoesIndexRoute,
  }

const AuthenticatedComunicacoesRouteWithChildren =
  AuthenticatedComunicacoesRoute._addFileChildren(
    AuthenticatedComunicacoesRouteChildren,
  )

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesEmpresasRoute: typeof AuthenticatedConfiguracoesEmpresasRoute
  AuthenticatedConfiguracoesPreferenciasRoute: typeof AuthenticatedConfiguracoesPreferenciasRoute
  AuthenticatedConfiguracoesProjetosRoute: typeof AuthenticatedConfiguracoesProjetosRoute
  AuthenticatedConfiguracoesTiposAusenciaRoute: typeof AuthenticatedConfiguracoesTiposAusenciaRoute
  AuthenticatedConfiguracoesProjetosConsolidarRoute: typeof AuthenticatedConfiguracoesProjetosConsolidarRoute
  AuthenticatedConfiguracoesProjetosImportarRoute: typeof AuthenticatedConfiguracoesProjetosImportarRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesEmpresasRoute:
      AuthenticatedConfiguracoesEmpresasRoute,
    AuthenticatedConfiguracoesPreferenciasRoute:
      AuthenticatedConfiguracoesPreferenciasRoute,
    AuthenticatedConfiguracoesProjetosRoute:
      AuthenticatedConfiguracoesProjetosRoute,
    AuthenticatedConfiguracoesTiposAusenciaRoute:
      AuthenticatedConfiguracoesTiposAusenciaRoute,
    AuthenticatedConfiguracoesProjetosConsolidarRoute:
      AuthenticatedConfiguracoesProjetosConsolidarRoute,
    AuthenticatedConfiguracoesProjetosImportarRoute:
      AuthenticatedConfiguracoesProjetosImportarRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedInteligenciaRouteChildren {
  AuthenticatedInteligenciaAlertasRoute: typeof AuthenticatedInteligenciaAlertasRoute
  AuthenticatedInteligenciaConfiguracaoRoute: typeof AuthenticatedInteligenciaConfiguracaoRoute
  AuthenticatedInteligenciaDashboardRoute: typeof AuthenticatedInteligenciaDashboardRoute
  AuthenticatedInteligenciaGovernancaRoute: typeof AuthenticatedInteligenciaGovernancaRoute
  AuthenticatedInteligenciaQualidadeRoute: typeof AuthenticatedInteligenciaQualidadeRoute
  AuthenticatedInteligenciaSupervisoresRoute: typeof AuthenticatedInteligenciaSupervisoresRoute
  AuthenticatedInteligenciaColaboradoresColaboradorIdRoute: typeof AuthenticatedInteligenciaColaboradoresColaboradorIdRoute
}

const AuthenticatedInteligenciaRouteChildren: AuthenticatedInteligenciaRouteChildren =
  {
    AuthenticatedInteligenciaAlertasRoute:
      AuthenticatedInteligenciaAlertasRoute,
    AuthenticatedInteligenciaConfiguracaoRoute:
      AuthenticatedInteligenciaConfiguracaoRoute,
    AuthenticatedInteligenciaDashboardRoute:
      AuthenticatedInteligenciaDashboardRoute,
    AuthenticatedInteligenciaGovernancaRoute:
      AuthenticatedInteligenciaGovernancaRoute,
    AuthenticatedInteligenciaQualidadeRoute:
      AuthenticatedInteligenciaQualidadeRoute,
    AuthenticatedInteligenciaSupervisoresRoute:
      AuthenticatedInteligenciaSupervisoresRoute,
    AuthenticatedInteligenciaColaboradoresColaboradorIdRoute:
      AuthenticatedInteligenciaColaboradoresColaboradorIdRoute,
  }

const AuthenticatedInteligenciaRouteWithChildren =
  AuthenticatedInteligenciaRoute._addFileChildren(
    AuthenticatedInteligenciaRouteChildren,
  )

interface AuthenticatedUsuariosRouteChildren {
  AuthenticatedUsuariosIdPermissoesRoute: typeof AuthenticatedUsuariosIdPermissoesRoute
}

const AuthenticatedUsuariosRouteChildren: AuthenticatedUsuariosRouteChildren = {
  AuthenticatedUsuariosIdPermissoesRoute:
    AuthenticatedUsuariosIdPermissoesRoute,
}

const AuthenticatedUsuariosRouteWithChildren =
  AuthenticatedUsuariosRoute._addFileChildren(
    AuthenticatedUsuariosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedBiExecutivoRoute: typeof AuthenticatedBiExecutivoRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedComunicacoesRoute: typeof AuthenticatedComunicacoesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardExecutivoRoute: typeof AuthenticatedDashboardExecutivoRoute
  AuthenticatedDeployRoute: typeof AuthenticatedDeployRoute
  AuthenticatedDocumentacaoRoute: typeof AuthenticatedDocumentacaoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedHomologacaoRoute: typeof AuthenticatedHomologacaoRoute
  AuthenticatedInteligenciaRoute: typeof AuthenticatedInteligenciaRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaAusenciaRoute: typeof AuthenticatedNovaAusenciaRoute
  AuthenticatedObservabilidadeRoute: typeof AuthenticatedObservabilidadeRoute
  AuthenticatedOcorrenciasPontoRoute: typeof AuthenticatedOcorrenciasPontoRoute
  AuthenticatedOperacaoAssistidaRoute: typeof AuthenticatedOperacaoAssistidaRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRoute
  AuthenticatedPainelRhRoute: typeof AuthenticatedPainelRhRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosAcaoRoute: typeof AuthenticatedPlanosAcaoRoute
  AuthenticatedProcessamentoRoute: typeof AuthenticatedProcessamentoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRouteWithChildren
  AuthenticatedAdminHardeningRoute: typeof AuthenticatedAdminHardeningRoute
  AuthenticatedAdministracaoAuditoriaForenseRoute: typeof AuthenticatedAdministracaoAuditoriaForenseRoute
  AuthenticatedAdministracaoCoordenacaoRoute: typeof AuthenticatedAdministracaoCoordenacaoRoute
  AuthenticatedAdministracaoGovernancaExclusoesRoute: typeof AuthenticatedAdministracaoGovernancaExclusoesRoute
  AuthenticatedAdministracaoHistoricoSenhasRoute: typeof AuthenticatedAdministracaoHistoricoSenhasRoute
  AuthenticatedAdministracaoIntegridadeDadosRoute: typeof AuthenticatedAdministracaoIntegridadeDadosRoute
  AuthenticatedAdministracaoInvestigacoesRoute: typeof AuthenticatedAdministracaoInvestigacoesRoute
  AuthenticatedAdministracaoPendenciasSupervisorRoute: typeof AuthenticatedAdministracaoPendenciasSupervisorRoute
  AuthenticatedAdministracaoPermissoesRoute: typeof AuthenticatedAdministracaoPermissoesRoute
  AuthenticatedAdministracaoVinculosManuaisRoute: typeof AuthenticatedAdministracaoVinculosManuaisRoute
  AuthenticatedColaboradoresImportacoesRoute: typeof AuthenticatedColaboradoresImportacoesRoute
  AuthenticatedColaboradoresImportarRoute: typeof AuthenticatedColaboradoresImportarRoute
  AuthenticatedColaboradoresReprocessarSupervisoresRoute: typeof AuthenticatedColaboradoresReprocessarSupervisoresRoute
  AuthenticatedCoordenacaoSupervisoresRoute: typeof AuthenticatedCoordenacaoSupervisoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedBiExecutivoRoute: AuthenticatedBiExecutivoRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedComunicacoesRoute: AuthenticatedComunicacoesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardExecutivoRoute: AuthenticatedDashboardExecutivoRoute,
  AuthenticatedDeployRoute: AuthenticatedDeployRoute,
  AuthenticatedDocumentacaoRoute: AuthenticatedDocumentacaoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedHomologacaoRoute: AuthenticatedHomologacaoRoute,
  AuthenticatedInteligenciaRoute: AuthenticatedInteligenciaRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaAusenciaRoute: AuthenticatedNovaAusenciaRoute,
  AuthenticatedObservabilidadeRoute: AuthenticatedObservabilidadeRoute,
  AuthenticatedOcorrenciasPontoRoute: AuthenticatedOcorrenciasPontoRoute,
  AuthenticatedOperacaoAssistidaRoute: AuthenticatedOperacaoAssistidaRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRoute,
  AuthenticatedPainelRhRoute: AuthenticatedPainelRhRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosAcaoRoute: AuthenticatedPlanosAcaoRoute,
  AuthenticatedProcessamentoRoute: AuthenticatedProcessamentoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRouteWithChildren,
  AuthenticatedAdminHardeningRoute: AuthenticatedAdminHardeningRoute,
  AuthenticatedAdministracaoAuditoriaForenseRoute:
    AuthenticatedAdministracaoAuditoriaForenseRoute,
  AuthenticatedAdministracaoCoordenacaoRoute:
    AuthenticatedAdministracaoCoordenacaoRoute,
  AuthenticatedAdministracaoGovernancaExclusoesRoute:
    AuthenticatedAdministracaoGovernancaExclusoesRoute,
  AuthenticatedAdministracaoHistoricoSenhasRoute:
    AuthenticatedAdministracaoHistoricoSenhasRoute,
  AuthenticatedAdministracaoIntegridadeDadosRoute:
    AuthenticatedAdministracaoIntegridadeDadosRoute,
  AuthenticatedAdministracaoInvestigacoesRoute:
    AuthenticatedAdministracaoInvestigacoesRoute,
  AuthenticatedAdministracaoPendenciasSupervisorRoute:
    AuthenticatedAdministracaoPendenciasSupervisorRoute,
  AuthenticatedAdministracaoPermissoesRoute:
    AuthenticatedAdministracaoPermissoesRoute,
  AuthenticatedAdministracaoVinculosManuaisRoute:
    AuthenticatedAdministracaoVinculosManuaisRoute,
  AuthenticatedColaboradoresImportacoesRoute:
    AuthenticatedColaboradoresImportacoesRoute,
  AuthenticatedColaboradoresImportarRoute:
    AuthenticatedColaboradoresImportarRoute,
  AuthenticatedColaboradoresReprocessarSupervisoresRoute:
    AuthenticatedColaboradoresReprocessarSupervisoresRoute,
  AuthenticatedCoordenacaoSupervisoresRoute:
    AuthenticatedCoordenacaoSupervisoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthNovaSenhaRoute: AuthNovaSenhaRoute,
  ApiPublicHooksEvolutionWhatsappWebhookRoute:
    ApiPublicHooksEvolutionWhatsappWebhookRoute,
  ApiPublicHooksProcessWhatsappOutboxRoute:
    ApiPublicHooksProcessWhatsappOutboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
