/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPainelRhRouteImport } from './routes/_authenticated/painel-rh'
import { Route as AuthenticatedOperacoesRouteImport } from './routes/_authenticated/operacoes'
import { Route as AuthenticatedOperacaoAssistidaRouteImport } from './routes/_authenticated/operacao-assistida'
import { Route as AuthenticatedNovaAusenciaRouteImport } from './routes/_authenticated/nova-ausencia'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedHomologacaoRouteImport } from './routes/_authenticated/homologacao'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDocumentacaoRouteImport } from './routes/_authenticated/documentacao'
import { Route as AuthenticatedDeployRouteImport } from './routes/_authenticated/deploy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComunicacoesRouteImport } from './routes/_authenticated/comunicacoes'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedConfiguracoesTiposAusenciaRouteImport } from './routes/_authenticated/configuracoes.tipos-ausencia'
import { Route as AuthenticatedConfiguracoesProjetosRouteImport } from './routes/_authenticated/configuracoes.projetos'
import { Route as AuthenticatedConfiguracoesEmpresasRouteImport } from './routes/_authenticated/configuracoes.empresas'
import { Route as AuthenticatedColaboradoresImportarRouteImport } from './routes/_authenticated/colaboradores_.importar'
import { Route as AuthenticatedColaboradoresImportacoesRouteImport } from './routes/_authenticated/colaboradores_.importacoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRhRoute = AuthenticatedPainelRhRouteImport.update({
  id: '/painel-rh',
  path: '/painel-rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacoesRoute = AuthenticatedOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacaoAssistidaRoute =
  AuthenticatedOperacaoAssistidaRouteImport.update({
    id: '/operacao-assistida',
    path: '/operacao-assistida',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaAusenciaRoute =
  AuthenticatedNovaAusenciaRouteImport.update({
    id: '/nova-ausencia',
    path: '/nova-ausencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomologacaoRoute =
  AuthenticatedHomologacaoRouteImport.update({
    id: '/homologacao',
    path: '/homologacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentacaoRoute =
  AuthenticatedDocumentacaoRouteImport.update({
    id: '/documentacao',
    path: '/documentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeployRoute = AuthenticatedDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicacoesRoute =
  AuthenticatedComunicacoesRouteImport.update({
    id: '/comunicacoes',
    path: '/comunicacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesTiposAusenciaRoute =
  AuthenticatedConfiguracoesTiposAusenciaRouteImport.update({
    id: '/tipos-ausencia',
    path: '/tipos-ausencia',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesProjetosRoute =
  AuthenticatedConfiguracoesProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesEmpresasRoute =
  AuthenticatedConfiguracoesEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedColaboradoresImportarRoute =
  AuthenticatedColaboradoresImportarRouteImport.update({
    id: '/colaboradores_/importar',
    path: '/colaboradores/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresImportacoesRoute =
  AuthenticatedColaboradoresImportacoesRouteImport.update({
    id: '/colaboradores_/importacoes',
    path: '/colaboradores/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/comunicacoes': typeof AuthenticatedComunicacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/painel-rh': typeof AuthenticatedPainelRhRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/colaboradores/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/colaboradores/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/comunicacoes': typeof AuthenticatedComunicacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deploy': typeof AuthenticatedDeployRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/operacoes': typeof AuthenticatedOperacoesRoute
  '/painel-rh': typeof AuthenticatedPainelRhRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/colaboradores/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/colaboradores/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/comunicacoes': typeof AuthenticatedComunicacoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deploy': typeof AuthenticatedDeployRoute
  '/_authenticated/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/homologacao': typeof AuthenticatedHomologacaoRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/nova-ausencia': typeof AuthenticatedNovaAusenciaRoute
  '/_authenticated/operacao-assistida': typeof AuthenticatedOperacaoAssistidaRoute
  '/_authenticated/operacoes': typeof AuthenticatedOperacoesRoute
  '/_authenticated/painel-rh': typeof AuthenticatedPainelRhRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/colaboradores_/importacoes': typeof AuthenticatedColaboradoresImportacoesRoute
  '/_authenticated/colaboradores_/importar': typeof AuthenticatedColaboradoresImportarRoute
  '/_authenticated/configuracoes/empresas': typeof AuthenticatedConfiguracoesEmpresasRoute
  '/_authenticated/configuracoes/projetos': typeof AuthenticatedConfiguracoesProjetosRoute
  '/_authenticated/configuracoes/tipos-ausencia': typeof AuthenticatedConfiguracoesTiposAusenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/auditoria'
    | '/ausencias'
    | '/colaboradores'
    | '/comunicacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/deploy'
    | '/documentacao'
    | '/historico'
    | '/homologacao'
    | '/notificacoes'
    | '/nova-ausencia'
    | '/operacao-assistida'
    | '/operacoes'
    | '/painel-rh'
    | '/relatorios'
    | '/roadmap'
    | '/saude'
    | '/usuarios'
    | '/colaboradores/importacoes'
    | '/colaboradores/importar'
    | '/configuracoes/empresas'
    | '/configuracoes/projetos'
    | '/configuracoes/tipos-ausencia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alertas'
    | '/auditoria'
    | '/ausencias'
    | '/colaboradores'
    | '/comunicacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/deploy'
    | '/documentacao'
    | '/historico'
    | '/homologacao'
    | '/notificacoes'
    | '/nova-ausencia'
    | '/operacao-assistida'
    | '/operacoes'
    | '/painel-rh'
    | '/relatorios'
    | '/roadmap'
    | '/saude'
    | '/usuarios'
    | '/colaboradores/importacoes'
    | '/colaboradores/importar'
    | '/configuracoes/empresas'
    | '/configuracoes/projetos'
    | '/configuracoes/tipos-ausencia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/auditoria'
    | '/_authenticated/ausencias'
    | '/_authenticated/colaboradores'
    | '/_authenticated/comunicacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/deploy'
    | '/_authenticated/documentacao'
    | '/_authenticated/historico'
    | '/_authenticated/homologacao'
    | '/_authenticated/notificacoes'
    | '/_authenticated/nova-ausencia'
    | '/_authenticated/operacao-assistida'
    | '/_authenticated/operacoes'
    | '/_authenticated/painel-rh'
    | '/_authenticated/relatorios'
    | '/_authenticated/roadmap'
    | '/_authenticated/saude'
    | '/_authenticated/usuarios'
    | '/_authenticated/colaboradores_/importacoes'
    | '/_authenticated/colaboradores_/importar'
    | '/_authenticated/configuracoes/empresas'
    | '/_authenticated/configuracoes/projetos'
    | '/_authenticated/configuracoes/tipos-ausencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-rh': {
      id: '/_authenticated/painel-rh'
      path: '/painel-rh'
      fullPath: '/painel-rh'
      preLoaderRoute: typeof AuthenticatedPainelRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacoes': {
      id: '/_authenticated/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof AuthenticatedOperacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao-assistida': {
      id: '/_authenticated/operacao-assistida'
      path: '/operacao-assistida'
      fullPath: '/operacao-assistida'
      preLoaderRoute: typeof AuthenticatedOperacaoAssistidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-ausencia': {
      id: '/_authenticated/nova-ausencia'
      path: '/nova-ausencia'
      fullPath: '/nova-ausencia'
      preLoaderRoute: typeof AuthenticatedNovaAusenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homologacao': {
      id: '/_authenticated/homologacao'
      path: '/homologacao'
      fullPath: '/homologacao'
      preLoaderRoute: typeof AuthenticatedHomologacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentacao': {
      id: '/_authenticated/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AuthenticatedDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deploy': {
      id: '/_authenticated/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AuthenticatedDeployRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicacoes': {
      id: '/_authenticated/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/comunicacoes'
      preLoaderRoute: typeof AuthenticatedComunicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/tipos-ausencia': {
      id: '/_authenticated/configuracoes/tipos-ausencia'
      path: '/tipos-ausencia'
      fullPath: '/configuracoes/tipos-ausencia'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTiposAusenciaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/projetos': {
      id: '/_authenticated/configuracoes/projetos'
      path: '/projetos'
      fullPath: '/configuracoes/projetos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesProjetosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/empresas': {
      id: '/_authenticated/configuracoes/empresas'
      path: '/empresas'
      fullPath: '/configuracoes/empresas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEmpresasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/colaboradores_/importar': {
      id: '/_authenticated/colaboradores_/importar'
      path: '/colaboradores/importar'
      fullPath: '/colaboradores/importar'
      preLoaderRoute: typeof AuthenticatedColaboradoresImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores_/importacoes': {
      id: '/_authenticated/colaboradores_/importacoes'
      path: '/colaboradores/importacoes'
      fullPath: '/colaboradores/importacoes'
      preLoaderRoute: typeof AuthenticatedColaboradoresImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesEmpresasRoute: typeof AuthenticatedConfiguracoesEmpresasRoute
  AuthenticatedConfiguracoesProjetosRoute: typeof AuthenticatedConfiguracoesProjetosRoute
  AuthenticatedConfiguracoesTiposAusenciaRoute: typeof AuthenticatedConfiguracoesTiposAusenciaRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesEmpresasRoute:
      AuthenticatedConfiguracoesEmpresasRoute,
    AuthenticatedConfiguracoesProjetosRoute:
      AuthenticatedConfiguracoesProjetosRoute,
    AuthenticatedConfiguracoesTiposAusenciaRoute:
      AuthenticatedConfiguracoesTiposAusenciaRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedComunicacoesRoute: typeof AuthenticatedComunicacoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeployRoute: typeof AuthenticatedDeployRoute
  AuthenticatedDocumentacaoRoute: typeof AuthenticatedDocumentacaoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedHomologacaoRoute: typeof AuthenticatedHomologacaoRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovaAusenciaRoute: typeof AuthenticatedNovaAusenciaRoute
  AuthenticatedOperacaoAssistidaRoute: typeof AuthenticatedOperacaoAssistidaRoute
  AuthenticatedOperacoesRoute: typeof AuthenticatedOperacoesRoute
  AuthenticatedPainelRhRoute: typeof AuthenticatedPainelRhRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedColaboradoresImportacoesRoute: typeof AuthenticatedColaboradoresImportacoesRoute
  AuthenticatedColaboradoresImportarRoute: typeof AuthenticatedColaboradoresImportarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedComunicacoesRoute: AuthenticatedComunicacoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeployRoute: AuthenticatedDeployRoute,
  AuthenticatedDocumentacaoRoute: AuthenticatedDocumentacaoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedHomologacaoRoute: AuthenticatedHomologacaoRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovaAusenciaRoute: AuthenticatedNovaAusenciaRoute,
  AuthenticatedOperacaoAssistidaRoute: AuthenticatedOperacaoAssistidaRoute,
  AuthenticatedOperacoesRoute: AuthenticatedOperacoesRoute,
  AuthenticatedPainelRhRoute: AuthenticatedPainelRhRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedColaboradoresImportacoesRoute:
    AuthenticatedColaboradoresImportacoesRoute,
  AuthenticatedColaboradoresImportarRoute:
    AuthenticatedColaboradoresImportarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
