DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_log_acao') THEN
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_PROMPT_SHOWN'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_ACCEPTED'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_DISMISSED'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_REMIND_LATER'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_NEVER'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE public.audit_log_acao ADD VALUE IF NOT EXISTS 'PWA_INSTALL_PREF_RESET'; EXCEPTION WHEN duplicate_object THEN NULL; END;
  END IF;
END$$;