
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'PROJETO_EXCLUIDO';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'PROJETO_ARQUIVADO_AUTOMATICO';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'PROJETOS_EXCLUSAO_LOTE';
