-- Add audit actions for Ocorrências de Ponto AMBEV
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'OCORRENCIA_PONTO_CRIADA';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'OCORRENCIA_PONTO_MANUAL_CRIADA';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'OCORRENCIA_PONTO_APROVADA';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'OCORRENCIA_PONTO_REPROVADA';
ALTER TYPE public.audit_action ADD VALUE IF NOT EXISTS 'OCORRENCIA_PONTO_CANCELADA';
