
ALTER TYPE public.notif_tipo ADD VALUE IF NOT EXISTS 'WHATSAPP_AUSENCIA_COLABORADOR';
ALTER TYPE public.notif_tipo ADD VALUE IF NOT EXISTS 'WHATSAPP_AUSENCIA_RH';
ALTER TYPE public.notif_tipo ADD VALUE IF NOT EXISTS 'WHATSAPP_AUSENCIA_SUPERVISOR';
