import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * ETAPA 1 — TESTES DE ROTAS
 *
 * We parse routeTree.gen.ts (regenerated by TanStack Router on every build)
 * and assert every critical URL resolves to a real route file. If any
 * critical path disappears, this test fails BEFORE Playwright ever runs —
 * catching the class of bug that produced the /colaboradores_/importar 404.
 */

const TREE = fs.readFileSync(
  path.resolve(__dirname, "../../src/routeTree.gen.ts"),
  "utf8",
);

// Paths as they appear on the URL bar (what users type / bookmark / share).
const CRITICAL_URLS = [
  "/",
  "/auth",
  "/dashboard",
  "/colaboradores",
  "/colaboradores/importar",
  "/colaboradores/importacoes",
  "/ausencias",
  "/nova-ausencia",
  "/comunicacoes",
  "/painel-rh",
  "/relatorios",
  "/auditoria",
  "/configuracoes",
  "/configuracoes/empresas",
  "/configuracoes/projetos",
  "/configuracoes/tipos-ausencia",
  "/homologacao",
  "/saude",
  "/documentacao",
  "/usuarios",
  "/alertas",
  "/historico",
];

describe("route registry", () => {
  it.each(CRITICAL_URLS)("registers %s in routeTree.gen.ts", (url) => {
    // TanStack emits FullPath keys like `'/configuracoes/empresas': typeof ...`
    // as well as leaf `path: '/foo'` entries. Match either.
    const escaped = url.replace(/[/-]/g, (c) => `\\${c}`);
    const fullPath = new RegExp(`['"]${escaped}['"]\\s*:`);
    const leafPath = new RegExp(`path:\\s*['"]${escaped}['"]`);
    const found = fullPath.test(TREE) || leafPath.test(TREE);
    expect(found, `missing route ${url}`).toBe(true);
  });

  it("colaboradores_ filename convention produces /colaboradores/importar (not /colaboradores_/importar)", () => {
    expect(TREE).toMatch(/path:\s*['"]\/colaboradores\/importar['"]/);
    expect(TREE).toMatch(/path:\s*['"]\/colaboradores\/importacoes['"]/);
    expect(TREE).not.toMatch(/path:\s*['"]\/colaboradores_\//);
  });

  it("gate is a pathless _authenticated layout (no duplicate '/')", () => {
    // The _authenticated layout must not claim '/', which would collide with index.tsx.
    const gateIndex = TREE.match(/_authenticated\/index/);
    expect(gateIndex).toBeNull();
  });
});
